# Generated by Django 3.1.1 on 2020-09-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HspApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
